const getStdServices = () => {
  return [
    {
      title: "Engine Oil Change",
      description: "Draining old engine oil and refilling with fresh oil",
      amount: 350,
      isChecked: true,
      cGST: 0,
      sGST: 0,
      comments: "",
      quantity: 1,
    },
    {
      title: "Oil Filter Replacement",
      description: "Replace oil filter to ensure clean oil flow",
      amount: 120,
      isChecked: true,
      cGST: 0,
      sGST: 0,
      comments: "",
      quantity: 1,
    },
    {
      title: "Air Filter Cleaning/Replacement",
      description: "Clean or replace air filter for proper combustion",
      amount: 80,
      isChecked: true,
      cGST: 0,
      sGST: 0,
      comments: "",
      quantity: 1,
    },
    {
      title: "Spark Plug Cleaning/Replacement",
      description: "Ensure ignition system functions correctly",
      amount: 60,
      isChecked: true,
      cGST: 0,
      sGST: 0,
      comments: "",
      quantity: 1,
    },
    {
      title: "Brake Cleaning & Adjustment",
      description: "Clean brake pads and adjust for proper braking",
      amount: 100,
      isChecked: true,
      cGST: 0,
      sGST: 0,
      comments: "",
      quantity: 1,
    },
    {
      title: "Clutch Adjustment",
      description: "Adjust clutch play for smooth operation",
      amount: 70,
      isChecked: true,
      cGST: 0,
      sGST: 0,
      comments: "",
      quantity: 1,
    },
    {
      title: "Chain Lubrication & Adjustment",
      description: "Lubricate and tighten/loosen chain as required",
      amount: 90,
      isChecked: true,
      cGST: 0,
      sGST: 0,
      comments: "",
      quantity: 1,
    },
    {
      title: "Battery Check",
      description: "Inspect battery health and terminals",
      amount: 50,
      isChecked: true,
      cGST: 0,
      sGST: 0,
      comments: "",
      quantity: 1,
    },
    {
      title: "Coolant Check/Top-up (if applicable)",
      description: "Check and refill coolant levels",
      amount: 150,
      isChecked: true,
      cGST: 0,
      sGST: 0,
      comments: "",
      quantity: 1,
    },
  ];
};
module.exports = getStdServices;
